CREATE TABLE [dbo].[EXAMPLE] (
	ID INT PRIMARY KEY,
	first_name NVARCHAR(255),
	last_name NVARCHAR(255)
);

INSERT INTO EXAMPLE2 VALUES (1, 'Dave', 'Stone');
INSERT INTO EXAMPLE2 VALUES (2, 'Lily', 'Bro');

SELECT * FROM EXAMPLE2;
